version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=mysecretpassword
    command: redis-server --requirepass mysecretpassword

  app:
    build: .
    container_name: node_app
    restart: always
    depends_on:
      - redis
    ports:
      - "8001:8001"
    environment:
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=mysecretpassword
    volumes:
      - .:/app
      - /app/node_modules
